#!/usr/bin/env bash

sudo yum install gcc -y
sudo yum install cpan -y
sudo yum install openssl -y
sudo yum install openssl-devel -y
sudo yum install git-all -y
sudo yum install pigz -y
sudo yum install unzip -y
sudo yum install wget -y
# For tests involving querying ucsc directly
sudo yum install mysql-devel -y

## For vcftools
sudo yum install autoconf -y
sudo yum install automake -y
git clone git://github.com/samtools/htslib.git
git clone git://github.com/samtools/bcftools.git
cd bcftools; make && sudo make install
cd ../htslib; make && sudo make install
cd ~/


# for perlbrew, in case you want to install a different perl version
sudo yum install patch -y

git clone git://github.com/LMDB/lmdb.git && cd lmdb/libraries/liblmdb
make
sudo make install
cd ~/

wget https://storage.googleapis.com/golang/go1.8.linux-amd64.tar.gz
tar -xvf go1.8.linux-amd64.tar.gz
sudo mv go /usr/local

go get github.com/akotlar/bystro-stats
go install github.com/akotlar/bystro-stats

go get github.com/akotlar/bystro-vcf
go install github.com/akotlar/bystro-vcf

go get github.com/akotlar/bystro-snp
go install github.com/akotlar/bystro-snp

(echo "" ; echo 'export PATH=$PATH:/usr/local/go/bin') >> ~/.bash_profile 
# export GOROOT=/usr/local/go
(echo ""; echo 'export GOPATH=$HOME/go') >> ~/.bash_profile
echo 'export PATH=$PATH:$HOME/go/bin/' >> ~/.bash_profile && source ~/.bash_profile

## make sure you have the right priveleges
mkdir -p $GOPATH/src/github.com

go get github.com/akotlar/bystro-stats
go install github.com/akotlar/bystro-stats

wget -O - https://install.perlbrew.pl | bash
(echo "" ; echo "source ~/perl5/perlbrew/etc/bashrc") >> ~/.bash_profile && source ~/.bash_profile
perlbrew install perl-5.26.0 && perlbrew switch perl-5.26.0

source ~/.bash_profile
perl -MCPAN -e 'my $c = "CPAN::HandleConfig"; $c->load(doit => 1, autoconfig => 1); $c->edit(prerequisites_policy => "follow"); $c->edit(build_requires_install_policy => "yes"); $c->commit'

"./install-perl-libs"

echo "REMEMBER TO INCREASE ULIMIT ABOVE 1024 IF RUNNING MANY FORKS"

mkdir logs
