---
assembly: mm10
chromosomes:
  - chr1
  - chr2
  - chr3
  - chr4
  - chr5
  - chr6
  - chr7
  - chr8
  - chr9
  - chr10
  - chr11
  - chr12
  - chr13
  - chr14
  - chr15
  - chr16
  - chr17
  - chr18
  - chr19
  - chrM
  - chrX
  - chrY
database_dir: "~"
files: "~"
files_dir: ~
statistics:
  dbSNPnameField: dbSNP.name
  exonicAlleleFunctionField: refSeq.exonicAlleleFunction
  outputExtensions:
    json: .statistics.json
    qc: .statistics.qc.tab
    tab: .statistics.tab
  refTrackField: ref
  siteTypeField: refSeq.siteType
  programPath: bystro-stats
temp_dir: "~"
fileProcessors:
  snp:
    args: --emptyField NA --minGq .95
    program: bystro-snp
  vcf:
    args: --emptyField NA --sample %sampleList% --keepPos --keepId
    program: bystro-vcf
tracks:
  - name: ref
    remote_dir: http://hgdownload.soe.ucsc.edu/goldenPath/mm10/chromosomes/
    remote_files:
      - chr1.fa.gz
      - chr2.fa.gz
      - chr3.fa.gz
      - chr4.fa.gz
      - chr5.fa.gz
      - chr6.fa.gz
      - chr7.fa.gz
      - chr8.fa.gz
      - chr9.fa.gz
      - chr10.fa.gz
      - chr11.fa.gz
      - chr12.fa.gz
      - chr13.fa.gz
      - chr14.fa.gz
      - chr15.fa.gz
      - chr16.fa.gz
      - chr17.fa.gz
      - chr18.fa.gz
      - chr19.fa.gz
      - chrM.fa.gz
      - chrX.fa.gz
      - chrY.fa.gz
    type: reference
  - features:
      - kgID
      - mRNA
      - spID
      - spDisplayID
      - refseq
      - protAcc
      - description
      - rfamAcc
      - name
      - name2
    name: refSeq
    sql_statement:
      SELECT * FROM mm10.refGene LEFT JOIN mm10.kgXref ON mm10.kgXref.refseq
      = mm10.refGene.name
    type: gene
    version: 1
  - name: phastCons
    remote_dir: http://hgdownload.cse.ucsc.edu/goldenPath/mm10/phastCons60way/mm10.60way.phastCons/
    remote_files:
      - chr1.phastCons60way.wigFix.gz
      - chr2.phastCons60way.wigFix.gz
      - chr3.phastCons60way.wigFix.gz
      - chr4.phastCons60way.wigFix.gz
      - chr5.phastCons60way.wigFix.gz
      - chr6.phastCons60way.wigFix.gz
      - chr7.phastCons60way.wigFix.gz
      - chr8.phastCons60way.wigFix.gz
      - chr9.phastCons60way.wigFix.gz
      - chr10.phastCons60way.wigFix.gz
      - chr11.phastCons60way.wigFix.gz
      - chr12.phastCons60way.wigFix.gz
      - chr13.phastCons60way.wigFix.gz
      - chr14.phastCons60way.wigFix.gz
      - chr15.phastCons60way.wigFix.gz
      - chr16.phastCons60way.wigFix.gz
      - chr17.phastCons60way.wigFix.gz
      - chr18.phastCons60way.wigFix.gz
      - chr19.phastCons60way.wigFix.gz
      - chrX.phastCons60way.wigFix.gz
      - chrY.phastCons60way.wigFix.gz
      - chrM.phastCons60way.wigFix.gz
    type: score
  - name: phyloP
    remote_dir: http://hgdownload.cse.ucsc.edu/goldenPath/mm10/phyloP60way/mm10.60way.phyloP60way/
    remote_files:
      - chr1.phyloP60way.wigFix.gz
      - chr2.phyloP60way.wigFix.gz
      - chr3.phyloP60way.wigFix.gz
      - chr4.phyloP60way.wigFix.gz
      - chr5.phyloP60way.wigFix.gz
      - chr6.phyloP60way.wigFix.gz
      - chr7.phyloP60way.wigFix.gz
      - chr8.phyloP60way.wigFix.gz
      - chr9.phyloP60way.wigFix.gz
      - chr10.phyloP60way.wigFix.gz
      - chr11.phyloP60way.wigFix.gz
      - chr12.phyloP60way.wigFix.gz
      - chr13.phyloP60way.wigFix.gz
      - chr14.phyloP60way.wigFix.gz
      - chr15.phyloP60way.wigFix.gz
      - chr16.phyloP60way.wigFix.gz
      - chr17.phyloP60way.wigFix.gz
      - chr18.phyloP60way.wigFix.gz
      - chr19.phyloP60way.wigFix.gz
      - chrX.phyloP60way.wigFix.gz
      - chrY.phyloP60way.wigFix.gz
      - chrM.phyloP60way.wigFix.gz
    type: score
  - build_field_transformations:
      alleleFreqs: split [,]
      alleleNs: split [,]
      alleles: split [,]
      func: split [,]
      observed: split [\/]
    features:
      - name
      - strand
      - observed
      - class
      - func
      - alleles
      - alleleNs: number
      - alleleFreqs: number
    name: dbSNP
    sql_statement: SELECT * FROM mm10.snp142
    type: sparse
