name: Perl Tidy & Critic Check

on:
  push:
    paths:
    - '**.pl'
    - '**.pm'
    - '**.t'
  pull_request:
    paths:
    - '**.pl'
    - '**.pm'
    - '**.t'

jobs:
  tidy-critic-check:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Perl environment
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.34'

    - name: Install Dependencies
      run: |
        cpanm --quiet Code::TidyAll Perl::Critic

    - name: Check out code
      uses: actions/checkout@v4

    - name: Run tidyall with Perl::Critic
      run: |
        cd perl
        tidyall -a
        if [[ $? != 0 ]]; then
          echo "Perl code is not tidy or has critic violations!"
          exit 1
        fi
