name: bystro-perl

on: [push, pull_request]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Setup perl and dependencies
      uses: ./.github/actions/setup-perl
      with:
        perl-version: '5.34'

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Test Bystro perl codebase
      run: |
        cd perl
        dzil authordeps | cpanm
        dzil listdeps | cpanm
        dzil test
