name: (Annotator) Build and Run Annotator Perl Dockerfile

on:
  release:
    types: [created]
  pull_request:
    paths:
      - "Dockerfile.perl"
  workflow_dispatch: # Optional: allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image from Local Context
        run: |
          docker build -t bystro-annotator -f Dockerfile.perl .

      - name: Run Docker Image and Capture Help Output
        continue-on-error: true # This is necessary because the help output returns a 255
        id: help-output
        run: |
          docker run --rm bystro-annotator &> help_output.txt

      - name: Assert Help Output Starts with Expected String
        run: |
          first_line=$(head -n 1 help_output.txt)
          if [[ "$first_line" == "usage: bystro-annotate.pl"* ]]; then
            echo "Help output assertion passed!"
          else
            echo "Help output assertion failed. Got: $first_line"
            exit 1
          fi

      - name: Upload Help Output as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: help-output
          path: help_output.txt
